"""add_training_labels

Revision ID: 77ab3e4b46f1
Revises: 31c1b60d2917
Create Date: 2026-04-11 22:25:32.366459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ab3e4b46f1'
down_revision: Union[str, Sequence[str], None] = '31c1b60d2917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('label_24h_snowfall_cm', sa.Float(), nullable=True),
    sa.Column('label_6h_wind_kmh', sa.Float(), nullable=True),
    sa.Column('label_12h_wind_kmh', sa.Float(), nullable=True),
    sa.Column('label_freezing_level_m', sa.Float(), nullable=True),
    sa.Column('label_precip_type', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_training_labels_location_time', 'training_labels', ['location_id', 'target_time'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_training_labels_location_time', table_name='training_labels')
    op.drop_table('training_labels')
    # ### end Alembic commands ###
